// import { alpha } from '@mui/material/styles';
import dayjs from "dayjs";
import CryptoJS from "crypto-js";

export const colors = {
  darkBlue: "#172D56",
  blue: "#2A72B9",
  white: "#ffffff",
  "blue.1": "#B3D9F5",
  "blue.2": "#85B7E1",
  "blue.3": "#5894CD",
  "blue.4": "#E3F2FD",
};
export const colorPalette = [
  colors.blue,
  colors["blue.2"],
  "#f47216", // Orange
  "#00e", // Blue
  "#1abc9c", // Teal
  "#f39c12", // Yellow-Orange
  "#8e44ad", // Purple
  "#e74c3c", // Red
  "#3498db", // Sky Blue
  "#2ecc71", // Green
  "#9b59b6", // Lavender
  "#16a085", // Dark Teal
  "#e67e22", // Burnt Orange
  "#d35400", // Dark Orange
  "#2980b9", // Medium Blue
  "#27ae60", // Rich Green
  "#c0392b", // Deep Red
  "#7f8c8d", // Gray
  "#34495e", // Navy Gray
  "#95a5a6", // Light Gray
  "#bdc3c7", // Soft Silver
  "#2c3e50", // Charcoal
];

export const getTodayDate = (format: string) => {
  const today = dayjs().format("YYYY-MM-DD");
  if (format) {
    return dayjs(today).format(format);
  }
  return today;
};

export function formatToMMDDYYYY(
  dateString?: string,
  time?: boolean,
  name?: boolean,
  backtype?: boolean
) {
  if (time) {
    if (!dateString) return dayjs().format("MM-DD-YYYY, HH:mm:ss");
    const date = dayjs(dateString);
    return date.isValid() ? date.format("MM-DD-YYYY, HH:mm:ss") : "-";
  } else if (name) {
    if (!dateString) return dayjs().format("MM-DD-YYYY");
    const date = dayjs(dateString);
    return date.isValid() ? date.format("MMM DD, YYYY") : "-";
  } else if (backtype) {
    if (!dateString) return dayjs().format("MM-DD-YYYY");
    const date = dayjs(dateString);
    return date.isValid() ? date.format("MM/DD/YYYY") : "-";
  } else {
    if (!dateString) return dayjs().format("MM-DD-YYYY");
    const date = dayjs(dateString);
    return date.isValid() ? date.format("MM-DD-YYYY") : "-";
  }
}

export const boarderRadius = {
  sm: "4px",
  md: "8px",
  lg: "16px",
  xl: "24px",
  "2xl": "32px",
  "3xl": "40px",
  card: "8px",
};
export function getCurrentCompanySlug(): string | undefined {
  if (typeof window === "undefined") return undefined; // SSR-safe
  const pathParts = window.location.pathname.split("/");
  // console.log(pathParts, 'pathPartspathParts');
  if (pathParts.length > 1 && pathParts[1] !== "intuityfe") {
    return pathParts?.includes("register") ? pathParts[2] : pathParts[1];
  }
  return undefined;
}

type PaymentConfig = {
  config_data_card?: Record<string, any>;
  config_data_ach?: Record<string, any>;
  [key: string]: any;
};
export const calculatePaymentAmount = ({
  amount,
  paymentType,
  cardType = "other",
  config = {},
}: {
  amount: number | string;
  paymentType: string;
  cardType?: string;
  config?: PaymentConfig;
}) => {
  const parseNum = (v: any) => {
    const n = parseFloat(v);
    return Number.isFinite(n) ? n : 0;
  };

  const base = parseNum(amount);
  // PHP only calculates when amount > 0 in the keyup path — follow that
  if (base <= 0)
    return {
      baseAmount: base,
      convenienceFee: 0.0,
      total: Number(base.toFixed(2)),
    };

  let conv = 0;
  const cardConfig = (config && config.config_data_card) || {};
  const achConfig = (config && config.config_data_ach) || {};

  // Helper to compute same branching logic as PHP for a group of (fixed, percentage, minimum)
  function computeFeeFromFields(baseAmount, fixedField, percField, minField) {
    const fixed = parseNum(fixedField);
    const perc = parseNum(percField);
    const minimum = parseNum(minField);

    if (fixed > 0 && perc > 0) {
      conv = (baseAmount * perc) / 100 + fixed;
      conv = Number(conv.toFixed(2)); // PHP does rounding here
      return conv > minimum ? conv : minimum;
    } else if (perc > 0) {
      conv = Number(((baseAmount * perc) / 100).toFixed(2));
      return conv > minimum ? conv : minimum;
    } else if (fixed > 0) {
      conv = Number(fixed.toFixed(2));
      return conv > minimum ? conv : minimum;
    } else {
      // fallback to minimum (even if zero)
      return minimum;
    }
  }

  if (paymentType === "card") {
    if (cardType === "amex") {
      conv = computeFeeFromFields(
        base,
        cardConfig.credit_card_amex_amount_convenience_fee,
        cardConfig.credit_card_amex_percentage_convenience_fee,
        cardConfig.credit_card_amex_minimum_amount_convenience_fee
      );
    } else {
      conv = computeFeeFromFields(
        base,
        cardConfig.credit_card_amount_convenience_fee,
        cardConfig.credit_card_percentage_convenience_fee,
        cardConfig.credit_card_minimum_amount_convenience_fee
      );
    }
  } else if (paymentType === "bank_account") {
    conv = computeFeeFromFields(
      base,
      achConfig.bank_amount_convenience_fee_ach,
      achConfig.bank_percentage_convenience_fee_ach,
      achConfig.bank_minimum_amount_convenience_fee_ach
    );
  }

  const convenienceFee = Number(conv.toFixed(2));
  const total = Number((base + convenienceFee).toFixed(2));

  return {
    baseAmount: Number(base.toFixed(2)),
    convenienceFee,
    total,
  };
};

export function decryptFunction(encrypted: string): string {
  const keyString = "Intuity";
  const ivString = "1234567891011121";

  try {
    // If the value is just a plain number/string with `**`, return masked
    if (!encrypted || /^\d+$/.test(encrypted) || encrypted.includes("**")) {
      return maskValue(encrypted);
    }

    // Decode base64 to bytes
    const ciphertext = CryptoJS.enc.Base64.parse(encrypted);

    // Create key/iv as WordArrays
    const key = CryptoJS.enc.Utf8.parse(keyString.padEnd(16, "\0"));
    const iv = CryptoJS.enc.Utf8.parse(ivString);

    // AES CTR decrypt
    const decrypted = CryptoJS.AES.decrypt({ ciphertext }, key, {
      iv,
      mode: CryptoJS.mode.CTR,
      padding: CryptoJS.pad.NoPadding,
    });

    const result = decrypted.toString(CryptoJS.enc.Utf8);

    return maskValue(result || encrypted);
  } catch (err) {
    return maskValue(encrypted);
  }
}

function maskValue(value: string): string {
  if (!value) return value;

  const last4 = value.slice(-4);
  return "********" + last4;
}

export const countriesList = [
  {
    id: 172,
    name: "Heard Island and Mcdonald Islands",
    region: "Antarctica",
    abbrev: "hm",
    phone_code: 0,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 22,
    name: "United States/Canada",
    region: "North America",
    abbrev: "us",
    phone_code: 1,
    is_two_way: 1,
    is_default: "0",
  },
  {
    id: 178,
    name: "Kazakhstan",
    region: "Asia",
    abbrev: "kz",
    phone_code: 7,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 35,
    name: "Egypt",
    region: "Africa",
    abbrev: "eg",
    phone_code: 20,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 99,
    name: "South Africa",
    region: "Africa",
    abbrev: "za",
    phone_code: 27,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 42,
    name: "Greece",
    region: "Europe",
    abbrev: "gr",
    phone_code: 30,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 75,
    name: "Netherlands",
    region: "Europe",
    abbrev: "nl",
    phone_code: 31,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 14,
    name: "Belgium",
    region: "Europe",
    abbrev: "be",
    phone_code: 32,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 39,
    name: "France",
    region: "Europe",
    abbrev: "fr",
    phone_code: 33,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 100,
    name: "Spain",
    region: "Europe",
    abbrev: "es",
    phone_code: 34,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 48,
    name: "Hungary",
    region: "Europe",
    abbrev: "hu",
    phone_code: 36,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 54,
    name: "Italy",
    region: "Europe",
    abbrev: "it",
    phone_code: 39,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 90,
    name: "Romania",
    region: "Europe",
    abbrev: "ro",
    phone_code: 40,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 104,
    name: "Switzerland",
    region: "Europe",
    abbrev: "ch",
    phone_code: 41,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 8,
    name: "Austria",
    region: "Europe",
    abbrev: "at",
    phone_code: 43,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 114,
    name: "United Kingdom",
    region: "Europe",
    abbrev: "gb",
    phone_code: 44,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 31,
    name: "Denmark",
    region: "Europe",
    abbrev: "dk",
    phone_code: 45,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 103,
    name: "Sweden",
    region: "Europe",
    abbrev: "se",
    phone_code: 46,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 80,
    name: "Norway",
    region: "Europe",
    abbrev: "no",
    phone_code: 47,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 87,
    name: "Poland",
    region: "Europe",
    abbrev: "pl",
    phone_code: 48,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 40,
    name: "Germany",
    region: "Europe",
    abbrev: "de",
    phone_code: 49,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 85,
    name: "Peru",
    region: "South America",
    abbrev: "pe",
    phone_code: 51,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 72,
    name: "Mexico",
    region: "North America",
    abbrev: "mx",
    phone_code: 52,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 149,
    name: "Cuba",
    region: "North America",
    abbrev: "cu",
    phone_code: 53,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 5,
    name: "Argentina",
    region: "South America",
    abbrev: "ar",
    phone_code: 54,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 19,
    name: "Brazil",
    region: "South America",
    abbrev: "br",
    phone_code: 55,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 24,
    name: "Chile",
    region: "South America",
    abbrev: "cl",
    phone_code: 56,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 26,
    name: "Colombia",
    region: "South America",
    abbrev: "co",
    phone_code: 57,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 118,
    name: "Venezuela",
    region: "South America",
    abbrev: "ve",
    phone_code: 58,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 68,
    name: "Malaysia",
    region: "Asia",
    abbrev: "my",
    phone_code: 60,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 7,
    name: "Australia",
    region: "Oceania",
    abbrev: "au",
    phone_code: 61,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 51,
    name: "Indonesia",
    region: "Asia",
    abbrev: "id",
    phone_code: 62,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 86,
    name: "Philippines",
    region: "Asia",
    abbrev: "ph",
    phone_code: 63,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 76,
    name: "New Zealand",
    region: "Oceania",
    abbrev: "nz",
    phone_code: 64,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 97,
    name: "Singapore",
    region: "Asia",
    abbrev: "sg",
    phone_code: 65,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 107,
    name: "Thailand",
    region: "Asia",
    abbrev: "th",
    phone_code: 66,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 91,
    name: "Russian Federation",
    region: "Asia",
    abbrev: "ru",
    phone_code: 70,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 56,
    name: "Japan",
    region: "Asia",
    abbrev: "jp",
    phone_code: 81,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 59,
    name: "Korea (South)",
    region: "Asia",
    abbrev: "kr",
    phone_code: 82,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 247,
    name: "Viet Nam",
    region: "Asia",
    abbrev: "vn",
    phone_code: 84,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 25,
    name: "China",
    region: "Asia",
    abbrev: "cn",
    phone_code: 86,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 110,
    name: "Turkey",
    region: "Asia",
    abbrev: "tr",
    phone_code: 90,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 50,
    name: "India",
    region: "Asia",
    abbrev: "in",
    phone_code: 91,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 82,
    name: "Pakistan",
    region: "Asia",
    abbrev: "pk",
    phone_code: 92,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 121,
    name: "Afghanistan",
    region: "Asia",
    abbrev: "af",
    phone_code: 93,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 101,
    name: "Sri Lanka",
    region: "Asia",
    abbrev: "lk",
    phone_code: 94,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 200,
    name: "Myanmar",
    region: "Asia",
    abbrev: "mm",
    phone_code: 95,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 174,
    name: "Iran, Islamic Republic of",
    region: "Asia",
    abbrev: "ir",
    phone_code: 98,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 232,
    name: "South Sudan",
    region: "Africa",
    abbrev: "ss",
    phone_code: 211,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 198,
    name: "Morocco",
    region: "Africa",
    abbrev: "ma",
    phone_code: 212,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 1,
    name: "Algeria",
    region: "Africa",
    abbrev: "dz",
    phone_code: 213,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 109,
    name: "Tunisia",
    region: "Africa",
    abbrev: "tn",
    phone_code: 216,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 186,
    name: "Libyan Arab Jamahiriya",
    region: "Africa",
    abbrev: "ly",
    phone_code: 218,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 162,
    name: "Gambia",
    region: "Africa",
    abbrev: "gm",
    phone_code: 220,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 96,
    name: "Senegal",
    region: "Africa",
    abbrev: "sn",
    phone_code: 221,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 192,
    name: "Mauritania",
    region: "Africa",
    abbrev: "mr",
    phone_code: 222,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 69,
    name: "Mali",
    region: "Africa",
    abbrev: "ml",
    phone_code: 223,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 169,
    name: "Guinea",
    region: "Africa",
    abbrev: "gn",
    phone_code: 224,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 148,
    name: "Cote D'Ivoire",
    region: "Africa",
    abbrev: "ci",
    phone_code: 225,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 135,
    name: "Burkina Faso",
    region: "Africa",
    abbrev: "bf",
    phone_code: 226,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 78,
    name: "Niger",
    region: "Africa",
    abbrev: "ne",
    phone_code: 227,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 239,
    name: "Togo",
    region: "Africa",
    abbrev: "tg",
    phone_code: 228,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 129,
    name: "Benin",
    region: "Africa",
    abbrev: "bj",
    phone_code: 229,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 71,
    name: "Mauritius",
    region: "Africa",
    abbrev: "mu",
    phone_code: 230,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 185,
    name: "Liberia",
    region: "Africa",
    abbrev: "lr",
    phone_code: 231,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 226,
    name: "Sierra Leone",
    region: "Africa",
    abbrev: "sl",
    phone_code: 232,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 41,
    name: "Ghana",
    region: "Africa",
    abbrev: "gh",
    phone_code: 233,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 79,
    name: "Nigeria",
    region: "Africa",
    abbrev: "ng",
    phone_code: 234,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 141,
    name: "Chad",
    region: "Africa",
    abbrev: "td",
    phone_code: 235,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 140,
    name: "Central African Republic",
    region: "Africa",
    abbrev: "cf",
    phone_code: 236,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 138,
    name: "Cameroon",
    region: "Africa",
    abbrev: "cm",
    phone_code: 237,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 139,
    name: "Cape Verde",
    region: "Africa",
    abbrev: "cv",
    phone_code: 238,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 222,
    name: "Sao Tome and Principe",
    region: "Africa",
    abbrev: "st",
    phone_code: 239,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 152,
    name: "Equatorial Guinea",
    region: "Africa",
    abbrev: "gq",
    phone_code: 240,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 161,
    name: "Gabon",
    region: "Africa",
    abbrev: "ga",
    phone_code: 241,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 145,
    name: "Congo",
    region: "Africa",
    abbrev: "cg",
    phone_code: 242,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 2,
    name: "Angola",
    region: "Africa",
    abbrev: "ao",
    phone_code: 244,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 170,
    name: "Guinea-Bissau",
    region: "Africa",
    abbrev: "gw",
    phone_code: 245,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 134,
    name: "British Indian Ocean Territory",
    region: "Asia",
    abbrev: "io",
    phone_code: 246,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 225,
    name: "Seychelles",
    region: "Africa",
    abbrev: "sc",
    phone_code: 248,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 233,
    name: "Sudan",
    region: "Africa",
    abbrev: "sd",
    phone_code: 249,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 215,
    name: "Rwanda",
    region: "Africa",
    abbrev: "rw",
    phone_code: 250,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 154,
    name: "Ethiopia",
    region: "Africa",
    abbrev: "et",
    phone_code: 251,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 230,
    name: "Somalia",
    region: "Africa",
    abbrev: "so",
    phone_code: 252,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 151,
    name: "Djibouti",
    region: "Africa",
    abbrev: "dj",
    phone_code: 253,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 58,
    name: "Kenya",
    region: "Africa",
    abbrev: "ke",
    phone_code: 254,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 106,
    name: "Tanzania",
    region: "Africa",
    abbrev: "tz",
    phone_code: 255,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 112,
    name: "Uganda",
    region: "Africa",
    abbrev: "ug",
    phone_code: 256,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 136,
    name: "Burundi",
    region: "Africa",
    abbrev: "bi",
    phone_code: 257,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 199,
    name: "Mozambique",
    region: "Africa",
    abbrev: "mz",
    phone_code: 258,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 251,
    name: "Zambia",
    region: "Africa",
    abbrev: "zm",
    phone_code: 260,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 67,
    name: "Madagascar",
    region: "Africa",
    abbrev: "mg",
    phone_code: 261,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 160,
    name: "French Southern Territories",
    region: "Antarctica",
    abbrev: "tf",
    phone_code: 262,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 252,
    name: "Zimbabwe",
    region: "Africa",
    abbrev: "zw",
    phone_code: 263,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 201,
    name: "Namibia",
    region: "Africa",
    abbrev: "na",
    phone_code: 264,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 188,
    name: "Malawi",
    region: "Africa",
    abbrev: "mw",
    phone_code: 265,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 184,
    name: "Lesotho",
    region: "Africa",
    abbrev: "ls",
    phone_code: 266,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 18,
    name: "Botswana",
    region: "Africa",
    abbrev: "bw",
    phone_code: 267,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 235,
    name: "Swaziland",
    region: "Africa",
    abbrev: "sz",
    phone_code: 268,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 144,
    name: "Comoros",
    region: "Africa",
    abbrev: "km",
    phone_code: 269,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 217,
    name: "Saint Helena",
    region: "Africa",
    abbrev: "sh",
    phone_code: 290,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 153,
    name: "Eritrea",
    region: "Africa",
    abbrev: "er",
    phone_code: 291,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 127,
    name: "Aruba",
    region: "North America",
    abbrev: "aw",
    phone_code: 297,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 156,
    name: "Faroe Islands",
    region: "Europe",
    abbrev: "fo",
    phone_code: 298,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 165,
    name: "Greenland",
    region: "North America",
    abbrev: "gl",
    phone_code: 299,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 164,
    name: "Gibraltar",
    region: "Europe",
    abbrev: "gi",
    phone_code: 350,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 88,
    name: "Portugal",
    region: "Europe",
    abbrev: "pt",
    phone_code: 351,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 64,
    name: "Luxembourg",
    region: "Europe",
    abbrev: "lu",
    phone_code: 352,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 52,
    name: "Ireland",
    region: "Europe",
    abbrev: "ie",
    phone_code: 353,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 49,
    name: "Iceland",
    region: "Europe",
    abbrev: "is",
    phone_code: 354,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 123,
    name: "Albania",
    region: "Europe",
    abbrev: "al",
    phone_code: 355,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 70,
    name: "Malta",
    region: "Europe",
    abbrev: "mt",
    phone_code: 356,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 29,
    name: "Cyprus",
    region: "Europe",
    abbrev: "cy",
    phone_code: 357,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 38,
    name: "Finland",
    region: "Europe",
    abbrev: "fi",
    phone_code: 358,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 21,
    name: "Bulgaria",
    region: "Europe",
    abbrev: "bg",
    phone_code: 359,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 63,
    name: "Lithuania",
    region: "Europe",
    abbrev: "lt",
    phone_code: 370,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 61,
    name: "Latvia",
    region: "Europe",
    abbrev: "lv",
    phone_code: 371,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 37,
    name: "Estonia",
    region: "Europe",
    abbrev: "ee",
    phone_code: 372,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 73,
    name: "Moldova",
    region: "Europe",
    abbrev: "md",
    phone_code: 373,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 6,
    name: "Armenia",
    region: "Europe",
    abbrev: "am",
    phone_code: 374,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 13,
    name: "Belarus",
    region: "Europe",
    abbrev: "by",
    phone_code: 375,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 125,
    name: "Andorra",
    region: "Europe",
    abbrev: "ad",
    phone_code: 376,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 195,
    name: "Monaco",
    region: "Europe",
    abbrev: "mc",
    phone_code: 377,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 221,
    name: "San Marino",
    region: "Europe",
    abbrev: "sm",
    phone_code: 378,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 244,
    name: "Ukraine",
    region: "Europe",
    abbrev: "ua",
    phone_code: 380,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 181,
    name: "Kosovo",
    region: "Europe",
    abbrev: "xk",
    phone_code: 381,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 197,
    name: "Montenegro",
    region: "Europe",
    abbrev: "me",
    phone_code: 382,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 28,
    name: "Croatia",
    region: "Europe",
    abbrev: "hr",
    phone_code: 385,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 98,
    name: "Slovenia",
    region: "Europe",
    abbrev: "si",
    phone_code: 386,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 132,
    name: "Bosnia and Herzegovina",
    region: "Europe",
    abbrev: "ba",
    phone_code: 387,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 66,
    name: "Macedonia",
    region: "Europe",
    abbrev: "mk",
    phone_code: 389,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 30,
    name: "Czech Republic",
    region: "Europe",
    abbrev: "cz",
    phone_code: 420,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 228,
    name: "Slovakia",
    region: "Europe",
    abbrev: "sk",
    phone_code: 421,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 187,
    name: "Liechtenstein",
    region: "Europe",
    abbrev: "li",
    phone_code: 423,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 155,
    name: "Falkland Islands (Malvinas)",
    region: "South America",
    abbrev: "fk",
    phone_code: 500,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 15,
    name: "Belize",
    region: "North America",
    abbrev: "bz",
    phone_code: 501,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 44,
    name: "Guatemala",
    region: "North America",
    abbrev: "gt",
    phone_code: 502,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 36,
    name: "El Salvador",
    region: "North America",
    abbrev: "sv",
    phone_code: 503,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 46,
    name: "Honduras",
    region: "North America",
    abbrev: "hn",
    phone_code: 504,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 77,
    name: "Nicaragua",
    region: "North America",
    abbrev: "ni",
    phone_code: 505,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 27,
    name: "Costa Rica",
    region: "North America",
    abbrev: "cr",
    phone_code: 506,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 83,
    name: "Panama",
    region: "North America",
    abbrev: "pa",
    phone_code: 507,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 219,
    name: "Saint Pierre and Miquelon",
    region: "North America",
    abbrev: "pm",
    phone_code: 508,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 171,
    name: "Haiti",
    region: "North America",
    abbrev: "ht",
    phone_code: 509,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 166,
    name: "Guadeloupe",
    region: "North America",
    abbrev: "gp",
    phone_code: 590,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 17,
    name: "Bolivia",
    region: "South America",
    abbrev: "bo",
    phone_code: 591,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 45,
    name: "Guyana",
    region: "South America",
    abbrev: "gy",
    phone_code: 592,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 34,
    name: "Ecuador",
    region: "South America",
    abbrev: "ec",
    phone_code: 593,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 158,
    name: "French Guiana",
    region: "South America",
    abbrev: "gf",
    phone_code: 594,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 84,
    name: "Paraguay",
    region: "South America",
    abbrev: "py",
    phone_code: 595,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 191,
    name: "Martinique",
    region: "North America",
    abbrev: "mq",
    phone_code: 596,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 102,
    name: "Suriname",
    region: "South America",
    abbrev: "sr",
    phone_code: 597,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 116,
    name: "Uruguay",
    region: "South America",
    abbrev: "uy",
    phone_code: 598,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 131,
    name: "Bonaire, Sint Eustatius and Saba",
    region: "North America",
    abbrev: "bq",
    phone_code: 599,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 238,
    name: "Timor-Leste",
    region: "Asia",
    abbrev: "tl",
    phone_code: 670,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 126,
    name: "Antarctica",
    region: "Antarctica",
    abbrev: "aq",
    phone_code: 672,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 20,
    name: "Brunei Darussalam",
    region: "Asia",
    abbrev: "bn",
    phone_code: 673,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 202,
    name: "Nauru",
    region: "Oceania",
    abbrev: "nr",
    phone_code: 674,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 211,
    name: "Papua New Guinea",
    region: "Oceania",
    abbrev: "pg",
    phone_code: 675,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 241,
    name: "Tonga",
    region: "Oceania",
    abbrev: "to",
    phone_code: 676,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 229,
    name: "Solomon Islands",
    region: "Oceania",
    abbrev: "sb",
    phone_code: 677,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 246,
    name: "Vanuatu",
    region: "Oceania",
    abbrev: "vu",
    phone_code: 678,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 157,
    name: "Fiji",
    region: "Oceania",
    abbrev: "fj",
    phone_code: 679,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 209,
    name: "Palau",
    region: "Oceania",
    abbrev: "pw",
    phone_code: 680,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 249,
    name: "Wallis and Futuna",
    region: "Oceania",
    abbrev: "wf",
    phone_code: 681,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 147,
    name: "Cook Islands",
    region: "Oceania",
    abbrev: "ck",
    phone_code: 682,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 206,
    name: "Niue",
    region: "Oceania",
    abbrev: "nu",
    phone_code: 683,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 220,
    name: "Samoa",
    region: "Oceania",
    abbrev: "ws",
    phone_code: 684,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 179,
    name: "Kiribati",
    region: "Oceania",
    abbrev: "ki",
    phone_code: 686,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 205,
    name: "New Caledonia",
    region: "Oceania",
    abbrev: "nc",
    phone_code: 687,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 243,
    name: "Tuvalu",
    region: "Oceania",
    abbrev: "tv",
    phone_code: 688,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 159,
    name: "French Polynesia",
    region: "Oceania",
    abbrev: "pf",
    phone_code: 689,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 240,
    name: "Tokelau",
    region: "Oceania",
    abbrev: "tk",
    phone_code: 690,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 194,
    name: "Micronesia, Federated States of",
    region: "Oceania",
    abbrev: "fm",
    phone_code: 691,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 190,
    name: "Marshall Islands",
    region: "Oceania",
    abbrev: "mh",
    phone_code: 692,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 180,
    name: "Korea, Democratic People's Republic of",
    region: "Asia",
    abbrev: "kp",
    phone_code: 850,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 47,
    name: "Hong Kong",
    region: "Asia",
    abbrev: "hk",
    phone_code: 852,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 65,
    name: "Macau",
    region: "Asia",
    abbrev: "mo",
    phone_code: 853,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 137,
    name: "Cambodia",
    region: "Asia",
    abbrev: "kh",
    phone_code: 855,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 183,
    name: "Lao People's Democratic Republic",
    region: "Asia",
    abbrev: "la",
    phone_code: 856,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 128,
    name: "Bangladesh",
    region: "Asia",
    abbrev: "bd",
    phone_code: 880,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 105,
    name: "Taiwan",
    region: "Asia",
    abbrev: "tw",
    phone_code: 886,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 189,
    name: "Maldives",
    region: "Asia",
    abbrev: "mv",
    phone_code: 960,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 62,
    name: "Lebanon",
    region: "Africa",
    abbrev: "lb",
    phone_code: 961,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 57,
    name: "Jordan",
    region: "Africa",
    abbrev: "jo",
    phone_code: 962,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 236,
    name: "Syrian Arab Republic",
    region: "Asia",
    abbrev: "sy",
    phone_code: 963,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 175,
    name: "Iraq",
    region: "Asia",
    abbrev: "iq",
    phone_code: 964,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 60,
    name: "Kuwait",
    region: "Asia",
    abbrev: "kw",
    phone_code: 965,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 95,
    name: "Saudi Arabia",
    region: "Africa",
    abbrev: "sa",
    phone_code: 966,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 120,
    name: "Yemen",
    region: "Asia",
    abbrev: "ye",
    phone_code: 967,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 81,
    name: "Oman",
    region: "Asia",
    abbrev: "om",
    phone_code: 968,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 210,
    name: "Palestinian Territory, Occupied",
    region: "Asia",
    abbrev: "ps",
    phone_code: 970,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 113,
    name: "United Arab Emirates",
    region: "Asia",
    abbrev: "ae",
    phone_code: 971,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 53,
    name: "Israel",
    region: "Asia",
    abbrev: "il",
    phone_code: 972,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 11,
    name: "Bahrain",
    region: "Asia",
    abbrev: "bh",
    phone_code: 973,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 89,
    name: "Qatar",
    region: "Africa",
    abbrev: "qa",
    phone_code: 974,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 130,
    name: "Bhutan",
    region: "Asia",
    abbrev: "bt",
    phone_code: 975,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 196,
    name: "Mongolia",
    region: "Asia",
    abbrev: "mn",
    phone_code: 976,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 203,
    name: "Nepal",
    region: "Asia",
    abbrev: "np",
    phone_code: 977,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 237,
    name: "Tajikistan",
    region: "Asia",
    abbrev: "tj",
    phone_code: 992,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 9,
    name: "Azerbaijan",
    region: "Europe",
    abbrev: "az",
    phone_code: 994,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 163,
    name: "Georgia",
    region: "Asia",
    abbrev: "ge",
    phone_code: 995,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 182,
    name: "Kyrgyzstan",
    region: "Asia",
    abbrev: "kg",
    phone_code: 996,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 117,
    name: "Uzbekistan",
    region: "Asia",
    abbrev: "uz",
    phone_code: 998,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 10,
    name: "Bahamas",
    region: "North America",
    abbrev: "bs",
    phone_code: 1242,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 12,
    name: "Barbados",
    region: "North America",
    abbrev: "bb",
    phone_code: 1246,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 3,
    name: "Anguilla",
    region: "North America",
    abbrev: "ai",
    phone_code: 1264,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 4,
    name: "Antigua and Barbuda",
    region: "North America",
    abbrev: "ag",
    phone_code: 1268,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 119,
    name: "Virgin Islands (British)",
    region: "North America",
    abbrev: "vg",
    phone_code: 1284,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 248,
    name: "Virgin Islands, U.s.",
    region: "North America",
    abbrev: "vi",
    phone_code: 1340,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 23,
    name: "Cayman Islands",
    region: "North America",
    abbrev: "ky",
    phone_code: 1345,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 16,
    name: "Bermuda",
    region: "North America",
    abbrev: "bm",
    phone_code: 1441,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 43,
    name: "Grenada",
    region: "North America",
    abbrev: "gd",
    phone_code: 1473,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 111,
    name: "Turks and Caicos Islands",
    region: "North America",
    abbrev: "tc",
    phone_code: 1649,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 74,
    name: "Montserrat",
    region: "North America",
    abbrev: "ms",
    phone_code: 1664,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 208,
    name: "Northern Mariana Islands",
    region: "Oceania",
    abbrev: "mp",
    phone_code: 1670,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 167,
    name: "Guam",
    region: "Oceania",
    abbrev: "gu",
    phone_code: 1671,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 124,
    name: "American Samoa",
    region: "Oceania",
    abbrev: "as",
    phone_code: 1684,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 93,
    name: "Saint Lucia",
    region: "North America",
    abbrev: "lc",
    phone_code: 1758,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 32,
    name: "Dominica",
    region: "North America",
    abbrev: "dm",
    phone_code: 1767,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 94,
    name: "Saint Vincent and The Grenadines",
    region: "North America",
    abbrev: "vc",
    phone_code: 1784,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 213,
    name: "Puerto Rico",
    region: "North America",
    abbrev: "pr",
    phone_code: 1787,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 33,
    name: "Dominican Republic",
    region: "North America",
    abbrev: "do",
    phone_code: 1809,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 108,
    name: "Trinidad and Tobago",
    region: "North America",
    abbrev: "tt",
    phone_code: 1868,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 92,
    name: "Saint Kitts And Nevis",
    region: "North America",
    abbrev: "kn",
    phone_code: 1869,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 55,
    name: "Jamaica",
    region: "North America",
    abbrev: "jm",
    phone_code: 1876,
    is_two_way: 0,
    is_default: "0",
  },
  {
    id: 242,
    name: "Turkmenistan",
    region: "Asia",
    abbrev: "tm",
    phone_code: 7370,
    is_two_way: 0,
    is_default: "0",
  },
];
